version: "3.8"
services:
  db:
    image: postgres:13.1
    container_name: db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
      - DATABASE_HOST=${DB_HOST}

  server:
    container_name: server
    build:
      context: ./server
      target: dev
    volumes:
      - ./server:/app
    ports:
      - "8080:8080"
      - "5005:5005"
    environment:
      - DATASOURCE_USER=${DB_USER}
      - DATASOURCE_PASSWORD=${DB_PASSWORD}
      - DATASOURCE_NAME=${DB_NAME}
      - DATASOURCE_HOST=${DB_HOST}

  client:
    container_name: client
    build:
      context: ./client
      dockerfile: Dockerfile
    volumes:
      - ./client:/app
    command: yarn start
    ports:
      - "3000:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true
