openapi: 3.0.0
info:
  title: keisanmondaisan
  version: '1.0'
  contact:
    name: Yasuaki Watanabe
    email: yasuaki640@gmail.com
  license:
    name: MIT
    url: 'http://opensource.org/licenses/mit-license.php'
  description: Operations of a server for keisanmondaisan app
servers:
  - url: 'https://localhost:8080'
paths:
  /auth:
    post:
      summary: ''
      operationId: post-auth
      tags:
        - auth
      responses:
        '200':
          $ref: "#/components/responses/200-OK"
      description: authorization for a user
      parameters: []
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                loginId:
                  type: string
                password:
                  type: string
        description: ''
components:
  schemas: {}
  securitySchemes: {}
  responses:
    200-OK:
      description: "OK"
      content:
        application/json:
          schema:
            type: object
            properties:
              status:
                type: number
              message:
                type: string