openapi: 3.0.0
tags:
  - name: auth
    description: Authorize a user operation
info:
  title: keisanmondaisan
  version: '1.0'
  contact:
    name: Yasuaki Watanabe
    email: yasuaki640@gmail.com
  license:
    name: MIT
    url: 'http://opensource.org/licenses/mit-license.php'
  description: Operations of a server for keisanmondaisan app
servers:
  - url: 'https://localhost:8080'
paths:
  /auth:
    post:
      summary: ''
      operationId: post-auth
      tags:
        - auth
      responses:
        '200':
          description: "OK"
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
          headers:
            Set-Cookie:
              schema:
                type: string
              description: contains session id
      description: authorization for a user
      parameters: []
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                loginId:
                  type: string
                password:
                  type: string
        description: ''
components:
  schemas:
    ClientError:
      type: object
      properties:
        errors:
          type: array
          items:
            type: object
            properties:
              message:
                type: string
                example: invalid_value
  securitySchemes: {}
  responses:
    4XX-ClientError:
      description: Bad request
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ClientError'
    5XX-ServerError:
      description: Internal server error
      content:
        application/json:
          schema:
            type: object
            properties:
              message:
                type: string
                example: Unexpected error occured
